source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'


target 'DeFrameApp' do
   use_frameworks!

      pod 'SwiftyJSON'
      pod 'SDWebImage'
      pod 'FacebookCore', :git => 'https://github.com/facebook/facebook-sdk-swift', :branch => 'master'
      pod 'FacebookLogin'
      pod 'FacebookShare'
      pod 'ApiAI'
      pod 'MBProgressHUD'
      pod 'JSQMessagesViewController'
      pod 'JSQSystemSoundPlayer'
      pod 'BubbleTransition', '~> 2.0.0'
      pod 'MaterialComponents'
      pod 'RMPZoomTransitionAnimator'
      pod 'DGRunkeeperSwitch', '~> 1.1.4'
      pod 'ScalingCarousel', '= 2.2'
      pod 'Tamamushi'
      pod 'FontAwesomeKit'
      pod 'ChameleonFramework/Swift'
     target 'DeFrameAppTests' do

   end

end
